name: Validate

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hacs:
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - uses: hacs/action@main
        with:
          category: integration
  hassfest:
    name: Home Assistant validation
    runs-on: ubuntu-latest
    steps:
      - uses: home-assistant/actions/hassfest@master
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - run: pip install -r requirements_test.txt
      - run: python -m unittest discover -s tests -v
